In [2]:
import numpy as np
escalar = 1.2
vector = np.array([1, 2, 3])
matriz = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9], 
    ])
tensor = np.array([
    [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9], 
    ]
    ,
    [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9], 
    ]
    ,
    [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9], 
    ]
])
print("todo ok")

todo ok


aqui se va a transponer

In [2]:
matriz_transpuesta = matriz.T

print(matriz_transpuesta)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [3]:
print(tensor.T)

[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


suma de matrices

In [4]:
print(matriz + matriz)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [5]:
print(tensor + tensor)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]]


multiplicacion por escalar

In [6]:
print(3*matriz)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [7]:
print(3*tensor)

[[[ 3  6  9]
  [12 15 18]
  [21 24 27]]

 [[ 3  6  9]
  [12 15 18]
  [21 24 27]]

 [[ 3  6  9]
  [12 15 18]
  [21 24 27]]]


sumar un escalar al numpy.array

In [13]:
print(matriz +2.76)
print(tensor +2.76)

[[ 3.76  4.76  5.76]
 [ 6.76  7.76  8.76]
 [ 9.76 10.76 11.76]]
[[[ 3.76  4.76  5.76]
  [ 6.76  7.76  8.76]
  [ 9.76 10.76 11.76]]

 [[ 3.76  4.76  5.76]
  [ 6.76  7.76  8.76]
  [ 9.76 10.76 11.76]]

 [[ 3.76  4.76  5.76]
  [ 6.76  7.76  8.76]
  [ 9.76 10.76 11.76]]]


multiplicacion entre matrices

In [16]:
print(matriz.dot(matriz))
#o tambien se puede lo siguiente
print() # aqui solo dejo un espacio
print(np.dot(matriz, matriz)) 

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


suma de vectores y matrices (broadcasting), lo que se hace es que el vector se repite (en este caso 3 veces) y se suma con cada fila

In [17]:
print(matriz+vector)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


crear una matriz identidad de cualquier dimension

In [18]:
A= np.eye(4)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
calcular la inversa

In [28]:
#HACK PARA QUE LOS NUMEROS CHICOS SEAN 0
np.set_printoptions(suppress=True)

B = np.array([
    [1, 4, 7],
    [7, 3, 5],
    [11, 13, 17]
])
inversa_B = np.linalg.inv(B)
print(inversa_B)
print(B.dot(inversa_B))

[[-0.10294118  0.16911765 -0.00735294]
 [-0.47058824 -0.44117647  0.32352941]
 [ 0.42647059  0.22794118 -0.18382353]]
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]


calcular determinante

In [31]:
determinante_matriz = np.linalg.det(matriz)
print(determinante_matriz)


6.66133814775094e-16


crear una diagonal

In [4]:
print(np.diag([1, 2, 3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]
